### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by CocoaPriest** [radianttap/CardPresentationController#1]
Carthage support would be great

**Comment by radianttap** [comment]
Please test and report back if anything is amis

**Comment by lonkly** [comment]
> Please test and report back if anything is amis

Dependency "CardPresentationController" has no shared framework schemes for any of the platforms: iOS

**Comment by radianttap** [comment]
Man, Xcode can be wonky. Scheme was already marked as shared, but it was not in git repo for some reason. Checked off and then on and now it's added.

Hopefully it's fine now.
