### ISSUE TITLE
Installation through CocoaPod gives error

### ISSUE THREAD

**Issue by keyhan76** [radianttap/CardPresentationController#10]
<img width="569" alt="Screen Shot 2019-03-31 at 09 57 37" src="https://user-images.githubusercontent.com/17951995/55285172-7802da80-539b-11e9-84e2-2bf5b3f445e5.png">

**Comment by radianttap** [comment]
Hm, I have already moved to CocoaPods 1.7 beta, so missed this.

Pls try again, I added both the new and old version key.

**Comment by keyhan76** [comment]
Ok, thanks.

**Comment by radianttap** [comment]
I assume that means it's working now :)
