### ISSUE TITLE
Can't dismiss all presented to root

### ISSUE THREAD

**Issue by AhmedYasserAbdElrhman** [radianttap/CardPresentationController#14]

**Comment by radianttap** [comment]
Can you provide more details..?

**Comment by AhmedYasserAbdElrhman** [comment]
This works fine 
`        self.view.window?.rootViewController?.dismiss(animated: true, completion: nil)
`
rather than 
`if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
   appDelegate.window?.rootViewController?.dismiss(animated: true, completion: nil)
}
`
